import { MongoClient, type Db } from "mongodb";
import { env } from "./env";
import { query, queryOne } from "./db";
import { now, HOUR_MS, DAY_MS } from "./clock";
import { getLectures } from "./lectures";

/**
 * Integration with the team's exam system (UnivAI-exam_system, port 3200).
 *
 * The exam system owns exams in MongoDB and knows nothing about our virtual
 * clock. Deadlines live HERE: a quiz is takeable for 24 hours after its
 * lecture ends, and the midterm for 3 days after week 4's lecture ends. We
 * gate access, hand the student over by exam id, and the exam system webhooks
 * the result + proctoring report back to /api/exams/callback.
 *
 * Its domain model needs a Student, a Curriculum, one Chapter per week, and an
 * Enrollment before any exam can exist — ensureExamWorld() seeds those once
 * and remembers the ids in a univai_link document.
 */

export const QUIZ_WINDOW_MS = 24 * HOUR_MS;
export const MID_WINDOW_MS = 3 * DAY_MS;
export const EXAM_SYSTEM_URL = env.EXAM_SYSTEM_URL;

const globalForMongo = globalThis as unknown as { univaiMongo?: MongoClient };

async function mongo(): Promise<Db> {
  if (!globalForMongo.univaiMongo) {
    globalForMongo.univaiMongo = await MongoClient.connect(env.MONGODB_URI);
  }
  return globalForMongo.univaiMongo.db();
}

export type ExamLink = {
  student_id: string;
  curriculum_id: string;
  /** week -> chapter id, so webhook payloads can be mapped back to a week */
  chapters: { week: number; chapter_id: string; title: string }[];
  mid_exam_id: string | null;
};

/** Seed the exam system's world once, and remember the ids. */
export async function ensureExamWorld(): Promise<ExamLink> {
  const db = await mongo();
  const links = db.collection("univai_link");

  const existing = await links.findOne<ExamLink & { _id: unknown }>({});
  if (existing?.mid_exam_id) return existing;

  const lectures = await getLectures();
  const studentName = env.STUDENT_NAME;

  // Student, Curriculum, Chapters, Enrollment — shapes match the exam system's
  // mongoose models (mongoose validates app-side; the DB accepts plain docs).
  const students = db.collection("students");
  let student = await students.findOne({ name: studentName });
  if (!student) {
    const inserted = await students.insertOne({
      name: studentName,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    student = { _id: inserted.insertedId, name: studentName };
  }

  const book = await queryOne<{ title: string | null; filename: string }>(
    "SELECT title, filename FROM books ORDER BY id DESC LIMIT 1"
  );
  const courseTitle = book?.title ?? book?.filename ?? "UnivAI Course";

  const curricula = db.collection("curricula");
  let curriculum = await curricula.findOne({ title: courseTitle });
  if (!curriculum) {
    const inserted = await curricula.insertOne({
      title: courseTitle,
      description: "One Book, One Month — generated by UnivAI",
      owner_student_id: student._id,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    curriculum = { _id: inserted.insertedId, title: courseTitle };
  }

  const chaptersCol = db.collection("chapters");
  const chapters: ExamLink["chapters"] = [];
  for (const lecture of lectures) {
    let chapter = await chaptersCol.findOne({
      curriculum_id: curriculum._id,
      number: lecture.week,
    });
    if (!chapter) {
      const inserted = await chaptersCol.insertOne({
        curriculum_id: curriculum._id,
        title: lecture.title,
        number: lecture.week,
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      chapter = { _id: inserted.insertedId };
    }
    chapters.push({
      week: lecture.week,
      chapter_id: chapter._id.toString(),
      title: lecture.title,
    });
  }

  const enrollments = db.collection("enrollments");
  const enrollment = await enrollments.findOne({
    student_id: student._id,
    curriculum_id: curriculum._id,
  });
  if (!enrollment) {
    await enrollments.insertOne({
      student_id: student._id,
      curriculum_id: curriculum._id,
      enrolled_at: new Date(),
      status: "active",
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  // The midterm is PRE-CREATED by the exam system (their createMid), then
  // started later by exam id — exactly the id-handshake the integration uses.
  let midExamId: string | null = null;
  const createMidRes = await fetch(`${EXAM_SYSTEM_URL}/api/exams/mid`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      curriculum_id: curriculum._id.toString(),
      title: "Midterm — Weeks 1 to 4",
      chapter_ids: chapters.map((chapter) => chapter.chapter_id),
      passing_mark: 5,
    }),
  }).catch(() => null);

  if (createMidRes?.ok) {
    const midExam = await db.collection("exams").findOne(
      { student_id: student._id, type: "mid" },
      { sort: { _id: -1 } }
    );
    midExamId = midExam?._id.toString() ?? null;
  }

  const link: ExamLink = {
    student_id: student._id.toString(),
    curriculum_id: curriculum._id.toString(),
    chapters,
    mid_exam_id: midExamId,
  };
  await links.updateOne({}, { $set: link }, { upsert: true });
  return link;
}

export type ExamStatus = {
  kind: "quiz" | "mid";
  week: number | null;
  title: string;
  opensAt: Date;
  closesAt: Date;
  state: "locked" | "open" | "missed" | "submitted";
  score: string | null;
  maxScore: string | null;
  flagged: boolean;
};

/** Every exam with its window (virtual clock) and result, for the /exams page. */
export async function getExamStatuses(): Promise<ExamStatus[]> {
  const [virtualNow, lectures] = await Promise.all([now(), getLectures()]);

  const grades = await query<{
    kind: string;
    week: number | null;
    score: string;
    max_score: string;
    flagged: boolean;
  }>("SELECT kind, week, score, max_score, flagged FROM grades");

  const statuses: ExamStatus[] = [];

  for (const lecture of lectures) {
    const opensAt = lecture.endsAt;
    const closesAt = new Date(opensAt.getTime() + QUIZ_WINDOW_MS);
    const grade = grades.find((g) => g.kind === "quiz" && g.week === lecture.week);

    let state: ExamStatus["state"] = "locked";
    if (grade) state = "submitted";
    else if (virtualNow >= closesAt) state = "missed";
    else if (virtualNow >= opensAt) state = "open";

    statuses.push({
      kind: "quiz",
      week: lecture.week,
      title: `Quiz ${lecture.week} — ${lecture.title}`,
      opensAt,
      closesAt,
      state,
      score: grade?.score ?? null,
      maxScore: grade?.max_score ?? null,
      flagged: grade?.flagged ?? false,
    });
  }

  const lastLecture = lectures[lectures.length - 1];
  if (lastLecture) {
    const opensAt = lastLecture.endsAt;
    const closesAt = new Date(opensAt.getTime() + MID_WINDOW_MS);
    const grade = grades.find((g) => g.kind === "midterm");

    let state: ExamStatus["state"] = "locked";
    if (grade) state = "submitted";
    else if (virtualNow >= closesAt) state = "missed";
    else if (virtualNow >= opensAt) state = "open";

    statuses.push({
      kind: "mid",
      week: null,
      title: "Midterm — Weeks 1 to 4",
      opensAt,
      closesAt,
      state,
      score: grade?.score ?? null,
      maxScore: grade?.max_score ?? null,
      flagged: grade?.flagged ?? false,
    });
  }

  return statuses;
}

/** Start (or resume) an exam and return the URL the student takes it at. */
export async function startExam(kind: "quiz" | "mid", week: number | null): Promise<string> {
  const statuses = await getExamStatuses();
  const status = statuses.find((s) => s.kind === kind && s.week === week);
  if (!status) throw new Error("No such exam.");
  if (status.state === "locked")
    throw new Error(`Not open yet — it opens after the lecture, ${status.opensAt.toISOString()}.`);
  if (status.state === "missed") throw new Error("The window for this exam has closed.");
  if (status.state === "submitted") throw new Error("You already submitted this exam.");

  const link = await ensureExamWorld();

  if (kind === "quiz") {
    const chapter = link.chapters.find((c) => c.week === week);
    if (!chapter) throw new Error("No chapter for that week.");
    const res = await fetch(`${EXAM_SYSTEM_URL}/api/exams/quiz/start`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ student_id: link.student_id, chapter_id: chapter.chapter_id }),
    });
    const exam = await res.json();
    if (!res.ok) throw new Error(exam.error ?? "The exam system refused to start the quiz.");
    return `${EXAM_SYSTEM_URL}/exam/${exam._id}`;
  }

  if (!link.mid_exam_id) throw new Error("The midterm was not created yet — is the exam system running?");
  const res = await fetch(`${EXAM_SYSTEM_URL}/api/exams/mid/${link.mid_exam_id}/start`, {
    method: "POST",
  });
  const exam = await res.json();
  if (!res.ok) throw new Error(exam.error ?? "The exam system refused to start the midterm.");
  return `${EXAM_SYSTEM_URL}/exam/${link.mid_exam_id}`;
}

/** Map a webhook payload back to (kind, week) using the seeded link doc. */
export async function resolveWeek(payload: {
  type: string;
  chapter_id: string | null;
  exam_id: string;
}): Promise<{ kind: "quiz" | "midterm"; week: number | null }> {
  const db = await mongo();
  const link = await db.collection("univai_link").findOne<ExamLink>({});
  if (payload.type === "quiz" && payload.chapter_id && link) {
    const chapter = link.chapters.find((c) => c.chapter_id === payload.chapter_id);
    return { kind: "quiz", week: chapter?.week ?? null };
  }
  return { kind: "midterm", week: null };
}
